debug: false
#web服务配置
server:
  context-path: /mornig
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: root
  #redis
redis:
  host: 127.0.0.1
  port: 6379
  pass:
logging:
  level: debug
